"""
Error package exports for the API layer.

Re-exports all ApiError subclasses so consumers can import either from
`api.errors` (this package) or `api.errors.exceptions` (the implementation
module). Current consumers use the latter; the former is kept as a
stable public surface.
"""

from api.errors.exceptions import (
    AccountConnectAuthError,
    AccountMisconfigured,
    AccountNotConnected,
    AccountNotFound,
    AccountOperationError,
    ApiError,
    AppCredentialsInvalid,
    AppCredentialsMissing,
    CredentialFileError,
    DatabaseConnectionError,
    DatabaseMigrationError,
    DatabaseQueryError,
    DraftCreationError,
    DraftListError,
    DraftSyncError,
    EmailContentFetchError,
    EmailFetchError,
    EmailListError,
    EmailNotInTrash,
    EmailSendError,
    EnvVarError,
    ExternalAPIError,
    Forbidden,
    MailboxNotFound,
    MailboxOperationError,
    MoveToTrashError,
    ReadStatusUpdateError,
    RecipientsMissing,
    SessionOperationError,
    SpamMoveError,
    SpamRestoreError,
    TokenDecryptionError,
    TokenEncryptionError,
    TokenIntegrityError,
    TrashOperationError,
    Unauthorized,
    UserNotFound,
    UserOperationError,
)

__all__ = [
    "AccountConnectAuthError",
    "AccountMisconfigured",
    "AccountNotConnected",
    "AccountNotFound",
    "AccountOperationError",
    "ApiError",
    "AppCredentialsInvalid",
    "AppCredentialsMissing",
    "CredentialFileError",
    "DatabaseConnectionError",
    "DatabaseMigrationError",
    "DatabaseQueryError",
    "DraftCreationError",
    "DraftListError",
    "DraftSyncError",
    "EmailContentFetchError",
    "EmailFetchError",
    "EmailListError",
    "EmailNotInTrash",
    "EmailSendError",
    "EnvVarError",
    "ExternalAPIError",
    "Forbidden",
    "MailboxNotFound",
    "MailboxOperationError",
    "MoveToTrashError",
    "ReadStatusUpdateError",
    "RecipientsMissing",
    "SessionOperationError",
    "SpamMoveError",
    "SpamRestoreError",
    "TokenDecryptionError",
    "TokenEncryptionError",
    "TokenIntegrityError",
    "TrashOperationError",
    "Unauthorized",
    "UserNotFound",
    "UserOperationError",
]
