"""
Error package exports for the API layer.
"""

from api.errors.exceptions import (
    AccountConnectAuthError,
    AccountMisconfigured,
    AccountNotConnected,
    AccountNotFound,
    ApiError,
    AppCredentialsInvalid,
    AppCredentialsMissing,
    CredentialFileError,
    DatabaseConnectionError,
    DatabaseMigrationError,
    DatabaseQueryError,
    EmailFetchError,
    EmailSendError,
    EnvVarError,
    ExternalAPIError,
    Forbidden,
    MailboxNotFound,
    RecipientsMissing,
    TokenDecryptionError,
    TokenIntegrityError,
    Unauthorized,
    UserNotFound,
)

__all__ = [
    "AccountConnectAuthError",
    "AccountMisconfigured",
    "AccountNotConnected",
    "AccountNotFound",
    "ApiError",
    "AppCredentialsInvalid",
    "AppCredentialsMissing",
    "CredentialFileError",
    "DatabaseConnectionError",
    "DatabaseMigrationError",
    "DatabaseQueryError",
    "EmailFetchError",
    "EmailSendError",
    "EnvVarError",
    "ExternalAPIError",
    "Forbidden",
    "MailboxNotFound",
    "RecipientsMissing",
    "TokenDecryptionError",
    "TokenIntegrityError",
    "Unauthorized",
    "UserNotFound",
]
